"""API-name stub lists used by install_shim. Pure data: each list is
(name, argc) tuples; OUT_PTR_STUBS additionally carries out-arg index,
byte count, and whether the OUT is a pointer-typed sentinel."""

LIKELY_STUBS = [
    # KMDF preview (real WDF needs a fake fn table; the stub at least
    # makes WdfVersionBind succeed so DriverEntry doesn't bail).
    ('WdfVersionBind', 4), ('WdfVersionUnbind', 4),
    ('WdfVersionBindClass', 4), ('WdfVersionUnbindClass', 4),
    # Stubs surfaced by the corpus baseline as missing:
    ('KeInitializeSpinLock', 1),
    ('KeSetSystemAffinityThread', 1),
    ('KeSetSystemAffinity', 1),  # legacy alias (Win7) — KeSetSystemAffinityThread is newer
    ('ExCreateCallback', 4),
    ('ExNotifyCallback', 3),
    ('ExRegisterCallback', 4),
    ('ExUnregisterCallback', 1),
    ('ObReferenceObjectByHandleWithTag', 7),
    ('ObfDereferenceObjectWithTag', 2),
    ('ExAllocatePool2', 3),
    ('ExAllocatePool3', 5),
    ('IoAttachDeviceToDeviceStack', 2),
    ('IoAttachDevice', 3),
    ('IoDetachDevice', 1),
    ('ExInitializeNPagedLookasideList', 7),
    ('ExInitializePagedLookasideList', 7),
    ('ExDeleteNPagedLookasideList', 1),
    ('ExDeletePagedLookasideList', 1),
    ('ExAllocateFromNPagedLookasideList', 1),
    ('ExFreeToNPagedLookasideList', 2),
    ('ExAllocateFromPagedLookasideList', 1),
    ('ExFreeToPagedLookasideList', 2),
    ('PsReferencePrimaryToken', 1),
    ('PsDereferencePrimaryToken', 1),
    ('PsReferenceImpersonationToken', 4),
    # Push locks / synchronisation
    ('ExInitializePushLock', 1),
    ('ExAcquirePushLockExclusive', 1), ('ExReleasePushLockExclusive', 1),
    ('ExAcquirePushLockShared', 1), ('ExReleasePushLockShared', 1),
    ('ExAcquirePushLockExclusiveEx', 2),
    ('ExReleasePushLockExclusiveEx', 2),
    ('ExAcquireResourceExclusiveLite', 2),
    ('ExAcquireResourceSharedLite', 2),
    ('ExReleaseResourceLite', 1),
    ('ExInitializeResourceLite', 1),
    ('ExDeleteResourceLite', 1),
    # Push-lock / spin-lock variants (Win8+) — some drivers use these
    # instead of the legacy spin-lock APIs.
    ('ExAcquireSpinLockExclusive', 1),
    ('ExAcquireSpinLockShared', 1),
    ('ExReleaseSpinLockExclusive', 2),
    ('ExReleaseSpinLockShared', 2),
    ('ExAcquireSpinLockExclusiveAtDpcLevel', 1),
    ('ExReleaseSpinLockExclusiveFromDpcLevel', 1),
    # SEH (x64)
    ('_C_specific_handler', 4), ('__C_specific_handler', 4),
    # Memory probes
    ('MmIsAddressValid', 1),
    ('MmIsNonPagedSystemAddressValid', 1),
    ('MmSecureVirtualMemory', 3),
    ('MmUnsecureVirtualMemory', 1),
    ('MmCopyVirtualMemory', 7),
    ('MmAllocatePagesForMdl', 4),
    ('MmAllocatePagesForMdlEx', 6),
    ('MmFreePagesFromMdl', 1),
    ('MmSizeOfMdl', 2),
    ('MmMapIoSpaceEx', 3),
    # Process / thread (often Speakeasy provides, but ensure)
    ('KeStackAttachProcess', 2), ('KeUnstackDetachProcess', 1),
    ('KeAttachProcess', 1), ('KeDetachProcess', 0),
    ('PsAcquireProcessExitSynchronization', 1),
    ('PsReleaseProcessExitSynchronization', 1),
    ('PsGetProcessExitStatus', 1),
    ('PsGetProcessSessionId', 1),
    ('PsIsProtectedProcess', 1),
    ('PsIsProtectedProcessLight', 1),
    ('PsSetCreateThreadNotifyRoutineEx', 2),
    ('PsSetCreateProcessNotifyRoutineEx2', 3),
    ('PsSetLoadImageNotifyRoutineEx', 2),
    # Generic ZW/NT counterparts
    ('ZwOpenProcess', 4), ('ZwTerminateProcess', 2),
    ('ZwOpenThread', 4),
    ('ZwOpenKey', 3), ('ZwCreateKey', 7),
    ('ZwQueryValueKey', 6), ('ZwSetValueKey', 6),
    ('ZwDeleteValueKey', 2), ('ZwEnumerateKey', 6),
    ('ZwEnumerateValueKey', 6),
    ('ZwFlushKey', 1), ('ZwDeleteKey', 1),
    ('ZwDeleteFile', 1), ('NtDeleteFile', 1),
    ('ZwQueryInformationProcess', 5),
    ('ZwCreateSection', 7), ('ZwMapViewOfSection', 10),
    ('ZwUnmapViewOfSection', 2),
    ('ZwLoadDriver', 1), ('ZwUnloadDriver', 1),
    # File system
    ('FsRtlIsNameInExpression', 4),
    ('FsRtlRegisterFileSystemFilterCallbacks', 2),
    # IRP related extras
    ('IoSetCompletionRoutine', 6),
    ('IoSetDeviceInterfaceState', 2),
    ('IoRegisterDeviceInterface', 4),
    ('IoGetDeviceProperty', 5),
    ('IoOpenDeviceRegistryKey', 4),
    ('IoOpenDeviceInterfaceRegistryKey', 3),
    ('IoGetDeviceInterfaces', 4),
    ('IoGetDeviceInterfaceAlias', 3),
    # CRT (kernel-mode)
    ('atoi', 1), ('atol', 1), ('strstr', 2), ('strchr', 2), ('strrchr', 2),
    ('strncmp', 3), ('strcmp', 2), ('_stricmp', 2), ('_strnicmp', 3),
    ('strlen', 1), ('strcpy', 2), ('strncpy', 3),
    ('strcat', 2), ('strncat', 3),
    ('wcslen', 1), ('wcscpy', 2), ('wcsncpy', 3),
    ('wcscat', 2), ('wcsncat', 3),
    ('wcscmp', 2), ('_wcsicmp', 2), ('wcsstr', 2),
    ('wcschr', 2), ('wcsrchr', 2),
    ('_snprintf', 4), ('_snwprintf', 4),
    ('_vsnprintf', 4), ('_vsnwprintf', 4),
    ('sprintf', 3), ('swprintf', 3),
    ('sprintf_s', 4), ('swprintf_s', 4),
    ('toupper', 1), ('tolower', 1),
    ('isdigit', 1), ('isalpha', 1), ('isspace', 1),
    ('rand', 0), ('srand', 1),
    ('qsort', 4), ('bsearch', 5),
    ('memchr', 3), ('memcmp', 3),
    # Time
    ('KeQuerySystemTimePrecise', 1),
    ('KeQueryInterruptTimePrecise', 1),
    ('KeQueryUnbiasedInterruptTime', 1),
    ('KeQueryUnbiasedInterruptTimePrecise', 1),
    # CPU info
    ('KeQueryActiveProcessorCount', 1),
    ('KeQueryActiveProcessorCountEx', 1),
    ('KeQueryMaximumProcessorCount', 0),
    ('KeQueryMaximumProcessorCountEx', 1),
    # Random / crypto
    ('SystemFunction036', 2),  # RtlGenRandom
    ('RtlRandomEx', 1),
    # Extra Rtl (mostly Speakeasy already has, but skip-if-exists handles that)
    ('RtlUpcaseUnicodeString', 3), ('RtlDowncaseUnicodeString', 3),
    ('RtlIntegerToUnicodeString', 3),
    ('RtlUnicodeStringToInteger', 3),
    ('RtlUnicodeToMultiByteSize', 3),
    ('RtlStringFromGUID', 2),
    ('RtlGUIDFromString', 2),
    ('RtlCharToInteger', 3),
    ('RtlHashUnicodeString', 4),
    ('RtlSecureZeroMemory', 2),
    ('RtlCheckRegistryKey', 2),
    ('RtlWriteRegistryValue', 6),
    ('RtlQueryRegistryValues', 5),
    ('RtlCreateRegistryKey', 2),
    ('RtlDeleteRegistryValue', 3),
    ('RtlCompareMemory', 3),
    ('RtlInitEmptyUnicodeString', 3),
    ('RtlInitEmptyAnsiString', 3),
    ('RtlFreeAnsiString', 1),
    ('RtlPrefixUnicodeString', 3),
    # Context capture / SEH-helper APIs — drivers occasionally call
    # RtlCaptureContext during init (for crash-dump hooks, anti-debug,
    # stack walks). No-op stub: they read back zeroed CONTEXT, which is
    # almost always benign (drivers either store the snapshot for later
    # or ignore it). Without the stub Speakeasy errors with
    # `unsupported_api` and the driver bails.
    ('RtlCaptureContext', 1),
    ('RtlCaptureStackBackTrace', 4),
    ('KeCapturePersistentThreadState', 6),
    # Object manager extras
    ('ObReferenceObjectByPointer', 4),
    ('ObRegisterCallbacks', 2), ('ObUnRegisterCallbacks', 1),
    ('ObGetFilterVersion', 0),
    # Etw (rarely used but harmless)
    ('EtwRegister', 4), ('EtwUnregister', 1), ('EtwWrite', 4),
    # Original super_tracer LIKELY_STUBS
    ('IoCreateFile', 11), ('IoCreateFileEx', 12), ('IoCreateFileSpecifyDeviceObjectHint', 12),
    ('IoGetDeviceObjectPointer', 4), ('IoCallDriver', 2), ('IofCallDriver', 2),
    ('IoRegisterDriverReinitialization', 3), ('IoRegisterBootDriverReinitialization', 3),
    ('IoRegisterShutdownNotification', 1), ('IoUnregisterShutdownNotification', 1),
    ('IoRegisterFsRegistrationChange', 2), ('IoRegisterPlugPlayNotification', 7),
    ('PsCreateSystemThread', 7), ('PsGetCurrentProcess', 0),
    ('PsGetCurrentProcessId', 0), ('PsGetCurrentThread', 0), ('PsGetCurrentThreadId', 0),
    ('PsGetThreadProcess', 1), ('PsGetProcessId', 1), ('PsGetProcessImageFileName', 1),
    ('IoGetCurrentProcess', 0), ('IoThreadToProcess', 1),
    ('PsSetCreateProcessNotifyRoutine', 2), ('PsSetCreateProcessNotifyRoutineEx', 2),
    ('PsSetCreateThreadNotifyRoutine', 1), ('PsSetLoadImageNotifyRoutine', 1),
    ('PsRemoveLoadImageNotifyRoutine', 1), ('PsRemoveCreateThreadNotifyRoutine', 1),
    ('PsLookupProcessByProcessId', 2), ('ObReferenceObjectByHandle', 6),
    ('ObfReferenceObject', 1), ('ObReferenceObject', 1),
    ('ObOpenObjectByName', 7), ('ObOpenObjectByPointer', 7),
    ('ObReferenceObjectByName', 8), ('ObSetSecurityObjectByPointer', 3),
    ('ObCloseHandle', 2), ('ObGetObjectType', 1), ('ObQueryNameString', 4),
    ('KeGetCurrentIrql', 0), ('KeRaiseIrqlToDpcLevel', 0), ('KeLowerIrql', 1),
    ('KfRaiseIrql', 1), ('KfLowerIrql', 1), ('KeRaiseIrql', 2),
    ('KeAcquireGuardedMutex', 1), ('KeReleaseGuardedMutex', 1),
    ('KeInitializeGuardedMutex', 1),
    ('KeAcquireSpinLockAtDpcLevel', 1), ('KeReleaseSpinLockFromDpcLevel', 1),
    ('KeAcquireSpinLock', 2), ('KeReleaseSpinLock', 2),
    ('KefAcquireSpinLockAtDpcLevel', 1), ('KefReleaseSpinLockFromDpcLevel', 1),
    ('ExAcquireRundownProtection', 1), ('ExReleaseRundownProtection', 1),
    ('ExGetPreviousMode', 0),
    ('ExInitializeFastMutex', 1), ('ExAcquireFastMutexUnsafe', 1), ('ExReleaseFastMutexUnsafe', 1),
    ('ProbeForRead', 3), ('ProbeForWrite', 3),
    ('MmGetSystemAddressForMdlSafe', 2), ('MmBuildMdlForNonPagedPool', 1),
    ('MmIsNonPagedSystemAddressValid', 1), ('MmGetSystemRoutineAddress', 1),
    ('MmAllocateNonCachedMemory', 1), ('MmFreeNonCachedMemory', 2),
    ('MmAllocateContiguousMemory', 2), ('MmFreeContiguousMemory', 1),
    ('MmGetPhysicalAddress', 1), ('MmMapIoSpace', 3), ('MmUnmapIoSpace', 2),
    ('IoCancelIrp', 1), ('IoStartNextPacket', 2),
    ('IoBuildSynchronousFsdRequest', 7), ('IoBuildDeviceIoControlRequest', 9),
    ('IoBuildAsynchronousFsdRequest', 6), ('IoMakeAssociatedIrp', 2), ('IoFreeIrp', 1),
    ('IoAllocateIrp', 2), ('IoInitializeIrp', 3),
    ('IoCompleteRequest', 2),
    ('IoQueueWorkItem', 4), ('IoAllocateWorkItem', 1), ('IoFreeWorkItem', 1),
    ('NtCreateFile', 11), ('NtOpenFile', 6), ('NtReadFile', 9), ('NtWriteFile', 9),
    ('NtSetInformationFile', 5), ('NtClose', 1), ('NtQueryDirectoryFile', 11),
    ('NtOpenSymbolicLinkObject', 3), ('NtQuerySymbolicLinkObject', 3),
    ('ZwQueryDirectoryFile', 11), ('ZwOpenSymbolicLinkObject', 3),
    ('ZwQuerySymbolicLinkObject', 3),
    ('ZwOpenDirectoryObject', 3), ('NtOpenDirectoryObject', 3),
    ('ZwQueryDirectoryObject', 7), ('NtQueryDirectoryObject', 7),
    # C runtime — _vsnprintf_s / _snprintf_s / vsnprintf_s / snprintf_s /
    # strncpy_s / strcat_s / wcscat_s have proper-impl stubs installed by
    # shim_c_runtime.py that walk the va_list, render the format, and
    # surface the actual string in the argv report. Don't override them
    # with zero-stubs. (strcat_s/wcscat_s were zero-stubs prior to
    # 2026-05-29; that silenced the entire DbgPrint output of any
    # driver whose logger concatenated via strcat_s before calling
    # DbgPrint(buf) — buf stayed all-zero so DbgPrint logged empties.)
    ('wcsncat_s', 4), ('wcsncpy_s', 4), ('strtok_s', 3),
    # Timer/DPC infrastructure
    ('KeInitializeTimerEx', 2), ('KeSetTimerEx', 4),
    ('KeInitializeTimer', 1), ('KeSetTimer', 3),
    ('KeCancelTimer', 1), ('KeReadStateTimer', 1),
    ('KeInitializeDpc', 3), ('KeInsertQueueDpc', 3),
    ('KeRemoveQueueDpc', 1),
    # File-system / filter-manager extras
    ('FltSetCallbackDataDirty', 1), ('FltDoCompletionProcessingWhenSafe', 5),
    ('FltGetDestinationFileNameInformation', 6),
    ('FltSetInformationFile', 6), ('FltIsDirectory', 3),
    ('FltLockUserBuffer', 1), ('FltGetRequestorProcessId', 1),
    # Image-verification + IRP utilities
    ('SeRegisterImageVerificationCallback', 5),
    ('SeUnregisterImageVerificationCallback', 1),
    ('IoVolumeDeviceToDosName', 2),
    ('IoThreadToProcess', 1),
    # Common WFP-kit pieces likely to be touched
    ('FwpmBfeStateGet0', 0), ('FwpmEngineOpen0', 5),
    ('FwpmEngineClose0', 1), ('FwpmTransactionBegin0', 2),
    ('FwpmTransactionCommit0', 1), ('FwpmTransactionAbort0', 1),
    ('FwpmSubLayerAdd0', 3), ('FwpmCalloutAdd0', 4),
    ('FwpmFilterAdd0', 4), ('FwpmBfeStateSubscribeChanges0', 4),
    ('FwpsCalloutRegister1', 3), ('FwpsCalloutRegister0', 3),
    ('FwpsFlowAssociateContext0', 4),
    # WoW64 / image-name lookup
    ('PsGetProcessWow64Process', 1),
    ('PsReferenceProcessFilePointer', 2),
    ('SeLocateProcessImageName', 2),
    ('PsGetProcessExitStatus', 1),
    ('PsGetProcessImageFileName', 1),
    ('PsGetProcessId', 1),
    ('PsGetProcessCreateTimeQuadPart', 1),
    ('PsGetProcessInheritedFromUniqueProcessId', 1),
    ('PsGetProcessPeb', 1),
    ('PsGetThreadProcess', 1), ('PsGetThreadProcessId', 1),
    ('PsGetThreadId', 1), ('PsGetCurrentThreadId', 0),
    ('PsLookupThreadByThreadId', 2),
    ('PsIsSystemThread', 1),
    # Object/handle attributes
    ('ObSetHandleAttributes', 3),
    ('CmCallbackGetKeyObjectID', 3), ('CmRegisterCallbackEx', 6),
    ('KeBugCheckEx', 5), ('KeBugCheck', 1),
    ('KeRegisterBugCheckCallback', 5), ('KeDeregisterBugCheckCallback', 1),
    ('KeRegisterBugCheckReasonCallback', 4),
    ('KeDeregisterBugCheckReasonCallback', 1),
    # GenericTable / AVL — see install_rtl_generic_table in shim.py for
    # proper-init versions that store the comparator and avoid invoking
    # an uninitialized callback later.
    ('ExSystemTimeToLocalTime', 2), ('KeQuerySystemTimePrecise', 1),
    ('KeQueryTickCount', 1), ('KeQueryInterruptTime', 0),
    ('RtlGetVersion', 1), ('RtlImageDirectoryEntryToData', 4),
    ('RtlImageNtHeader', 1), ('RtlGetNtSystemRoot', 0),
    ('RtlCompareUnicodeString', 3), ('RtlEqualUnicodeString', 3),
    ('RtlAppendUnicodeStringToString', 2), ('RtlAppendUnicodeToString', 2),
    ('RtlCopyUnicodeString', 2), ('RtlVolumeDeviceToDosName', 2),
    ('RtlIsNameLegalDOS8Dot3', 3),
    ('IoIs32bitProcess', 1),
    ('IoFileObjectType', 0), ('PsProcessType', 0), ('PsThreadType', 0),
    ('IoDriverObjectType', 0), ('IoDeviceObjectType', 0),
    ('PsInitialSystemProcess', 0), ('PsLoadedModuleList', 0),
    ('IoVerifierKeAcquireSpinLockAtDpcLevel', 1), ('PsIsSystemThread', 1),
]

HAL_STUBS = [
    ('KeStallExecutionProcessor', 1), ('KeQueryPerformanceCounter', 1),
    ('HalGetBusDataByOffset', 5), ('HalSetBusDataByOffset', 5),
    ('HalGetBusData', 4), ('HalAssignSlotResources', 4),
    ('READ_PORT_UCHAR', 1), ('WRITE_PORT_UCHAR', 2),
    ('READ_PORT_USHORT', 1), ('WRITE_PORT_USHORT', 2),
    ('READ_PORT_ULONG', 1), ('WRITE_PORT_ULONG', 2),
    ('KeRaiseIrqlToDpcLevel', 0),
    ('HalMakeBeep', 1), ('HalQuerySystemInformation', 4),
    ('HalDisplayString', 1), ('HalGetInterruptVector', 6),
    ('HalSetBusData', 4),
    ('KeQueryActiveProcessorCount', 1),
    ('KeQueryActiveProcessorCountEx', 1),
]

ENUMERATORS = [
    ('ZwEnumerateKey', 6), ('NtEnumerateKey', 6),
    ('ZwEnumerateValueKey', 6), ('NtEnumerateValueKey', 6),
    ('ZwQueryDirectoryFile', 11), ('NtQueryDirectoryFile', 11),
    ('IoEnumerateDeviceObjectList', 4),
    ('IoEnumerateRegisteredFiltersList', 4),
]

OUT_PTR_STUBS = [
    # (name, argc, out_arg_idx, bytes_to_write, is_pointer_out)
    ('KeQuerySystemTime',                1, 0, 8, False),
    ('KeQueryUnbiasedInterruptTime',     1, 0, 8, False),
    ('KeQueryUnbiasedInterruptTimePrecise', 1, 0, 8, False),
    ('KeQueryInterruptTimePrecise',      1, 0, 8, False),
    ('KeQueryPerformanceCounter',        1, 0, 8, False),
    ('ExSystemTimeToLocalTime',          2, 1, 8, False),
    ('PsLookupProcessByProcessId',       2, 1, 8, True),
    ('PsLookupThreadByThreadId',         2, 1, 8, True),
    ('ObReferenceObjectByHandle',        6, 4, 8, True),
    ('ObReferenceObjectByName',          8, 6, 8, True),
    ('ObOpenObjectByName',               7, 6, 8, True),
    ('ObOpenObjectByPointer',            7, 6, 8, True),
    ('IoCreateFile',                    11, 0, 8, True),
    ('IoCreateFileEx',                  12, 0, 8, True),
    ('NtCreateFile',                    11, 0, 8, True),
    ('ZwCreateFile',                    11, 0, 8, True),
    ('NtOpenFile',                       6, 0, 8, True),
    ('ZwOpenFile',                       6, 0, 8, True),
    ('NtOpenKey',                        3, 0, 8, True),
    ('ZwOpenKey',                        3, 0, 8, True),
    ('NtCreateKey',                      7, 0, 8, True),
    ('ZwCreateKey',                      7, 0, 8, True),
    ('NtOpenProcess',                    4, 0, 8, True),
    ('ZwOpenProcess',                    4, 0, 8, True),
    ('NtOpenThread',                     4, 0, 8, True),
    ('ZwOpenThread',                     4, 0, 8, True),
    ('NtOpenSymbolicLinkObject',         3, 0, 8, True),
    ('ZwOpenSymbolicLinkObject',         3, 0, 8, True),
    ('IoGetDeviceObjectPointer',         4, 2, 8, True),
    ('MmGetSystemRoutineAddress',        1, None, 0, False),  # returns ptr in retval
]
