"""Emit a self-contained Ghidra Java script (GhidraScript) that carries the
ktrace findings into a Ghidra database.

The output is a `.java` file the user drops into `ghidra_scripts/` and
runs from Script Manager. It applies, by default:

  1. PRE comments at every traced API call site:
       "ntoskrnl.IoCreateDevice(drv=0x..., name='\\Device\\Foo') -> SUCCESS"
     (PRE because EOL crowds the listing line; PRE renders above the
      instruction with its own width budget.)
  2. Function labels for MajorFunction[] dispatchers, registered
     callbacks (CmRegisterCallback, Ps*Notify, ObRegisterCallbacks,
     PsCreateSystemThread starts), and reinit routines.

Addresses are emitted as **RVAs** (PC - ImageBase) so the script is
robust against rebasing — at apply-time it adds the live image base.

A header check verifies the script is being applied to the binary whose
SHA-256 matches the trace. Mismatch -> warns, prompts to continue.
"""
from __future__ import annotations
import json
import re
from pathlib import Path


_JAVA_HEADER = r"""// Auto-generated by ktrace --ghidra-export.
// Sample SHA-256: %(sha256)s
// Generated at:   %(timestamp)s
//
// Drop into <project>/ghidra_scripts/ and run via Script Manager.
// Annotations are applied to the *currentProgram* — open the matching
// binary first.
//
// Applies:
//   * %(n_comments)d PRE comments at traced API call sites
//   * %(n_labels)d   labels for dispatchers / callbacks / reinit routines
//
// Re-running is safe: existing PRE comments get the ktrace text appended
// after a newline + "ktrace: "; labels are skipped if they already exist.

import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.CodeUnit;
import ghidra.program.model.listing.CommentType;
import ghidra.program.model.listing.Listing;
import ghidra.program.model.symbol.SourceType;

public class %(class_name)s extends GhidraScript {

    private static final String EXPECTED_SHA256 = "%(sha256)s";

    // RVA, type ("PRE"|"EOL"|"POST"|"PLATE"|"REPEATABLE"), text
    private static final Object[][] COMMENTS = {
%(comments_block)s
    };

    // RVA, name
    private static final Object[][] LABELS = {
%(labels_block)s
    };

    @Override
    public void run() throws Exception {
        if (currentProgram == null) {
            println("ktrace-import: no current program");
            return;
        }
        long base = currentProgram.getImageBase().getOffset();
        println(String.format(
            "ktrace-import: target %%s, imageBase=0x%%x",
            currentProgram.getName(), base));

        // SHA-256 sanity check.
        String execSha = currentProgram.getExecutableSHA256();
        if (execSha != null && !execSha.equalsIgnoreCase(EXPECTED_SHA256)) {
            boolean cont = askYesNo("ktrace-import",
                "SHA-256 mismatch.\n"
                + "Expected:  " + EXPECTED_SHA256 + "\n"
                + "Current:   " + execSha + "\n"
                + "Apply anyway?");
            if (!cont) {
                println("ktrace-import: aborted by user");
                return;
            }
        }

        Listing listing = currentProgram.getListing();
        int appliedComments = 0, appliedLabels = 0, skipped = 0;

        for (Object[] row : COMMENTS) {
            long rva = (Long) row[0];
            String type = (String) row[1];
            String text = (String) row[2];
            Address a;
            try {
                a = currentProgram.getImageBase().add(rva);
            } catch (Exception e) {
                skipped++;
                continue;
            }
            // CommentType enum replaced the deprecated int constants
            // (CodeUnit.{EOL,PLATE,PRE,POST,REPEATABLE}_COMMENT) in
            // Ghidra 11.x; the old API is `@Deprecated(forRemoval)`.
            CommentType kind;
            switch (type) {
                case "PRE":        kind = CommentType.PRE; break;
                case "POST":       kind = CommentType.POST; break;
                case "PLATE":      kind = CommentType.PLATE; break;
                case "REPEATABLE": kind = CommentType.REPEATABLE; break;
                case "EOL":        kind = CommentType.EOL; break;
                default:           kind = CommentType.PRE;
            }
            CodeUnit cu = listing.getCodeUnitAt(a);
            if (cu == null) {
                cu = listing.getCodeUnitContaining(a);
            }
            if (cu == null) {
                skipped++;
                continue;
            }
            String existing = cu.getComment(kind);
            String marker = "ktrace: ";
            String combined;
            if (existing == null) {
                combined = marker + text;
            } else if (existing.contains(marker + text)) {
                // Already applied — leave alone.
                continue;
            } else {
                combined = existing + "\n" + marker + text;
            }
            cu.setComment(kind, combined);
            appliedComments++;
        }

        for (Object[] row : LABELS) {
            long rva = (Long) row[0];
            String name = (String) row[1];
            Address a;
            try {
                a = currentProgram.getImageBase().add(rva);
            } catch (Exception e) {
                skipped++;
                continue;
            }
            try {
                // createLabel(addr, name, makePrimary, sourceType)
                createLabel(a, name, true, SourceType.USER_DEFINED);
                appliedLabels++;
            } catch (Exception e) {
                // Already exists at that addr — non-fatal.
                skipped++;
            }
        }

        println(String.format(
            "ktrace-import: applied %%d comments + %%d labels (%%d skipped)",
            appliedComments, appliedLabels, skipped));
    }
}
"""


def _java_string(s):
    """Escape a Python string for embedding in a Java string literal."""
    if s is None:
        return '""'
    out = []
    for ch in s:
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ch == '\n':
            out.append('\\n')
        elif ch == '\r':
            out.append('\\r')
        elif ch == '\t':
            out.append('\\t')
        elif ord(ch) < 0x20:
            out.append(f'\\u{ord(ch):04x}')
        elif ord(ch) > 0x7E:
            # Java string literal supports \uXXXX for non-ASCII.
            out.append(f'\\u{ord(ch):04x}')
        else:
            out.append(ch)
    return '"' + ''.join(out) + '"'


def _sanitize_label(name):
    """Ghidra labels can be alphanumeric + underscore + `:` for namespace.
    Replace anything else with `_`."""
    return re.sub(r'[^A-Za-z0-9_]', '_', name)[:120]


def collect_annotations(emu, trace_log_text, mf_table, drv_fields,
                        callbacks, image_base, sha256,
                        jsonl_path=None):
    """Build the list of (rva, type, text) and (rva, label_name) tuples.

    Args:
      emu: speakeasy emulator (for get_report())
      trace_log_text: the rendered trace log (used as a fallback source;
                      we prefer the API report)
      mf_table: dict {MajorFunction index: address}
      drv_fields: dict of DriverObject pointer fields
      callbacks: list of (kind, fn_addr, args) tuples from invoke.discover_callbacks
      image_base: VA of image base (e.g. 0x140000000)
      sha256: hex string

    Returns:
      (comments, labels) — lists of tuples ready for emit()
    """
    import decode
    comments = []
    labels = []
    seen_label_addrs = set()

    def add_label(addr, name):
        if not addr or addr in seen_label_addrs:
            return
        rva = addr - image_base
        if rva < 0 or rva > 0xFFFFFFFF:
            return
        seen_label_addrs.add(addr)
        labels.append((rva, _sanitize_label(name)))

    def add_comment(addr, text, kind='PRE'):
        if not addr or not text:
            return
        rva = addr - image_base
        if rva < 0 or rva > 0xFFFFFFFF:
            return
        comments.append((rva, kind, text))

    # 1. EOL comments at every traced API call site, deduplicated by PC.
    # Drivers that walk all PIDs at boot generate 100k+ identical
    # PsLookupProcessByProcessId calls at the same PC — collapse those
    # into one comment with a "×N" suffix instead of 100k Object[] rows.
    pc_to_first = {}    # pc -> rendered line (first occurrence)
    pc_count = {}       # pc -> hit count
    pc_order = []       # insertion order — preserves rough trace order
    report = emu.get_report() if emu else {'entry_points': []}
    for ent in report.get('entry_points', []):
        for a in ent.get('apis', []):
            pc = a.get('pc')
            api_full = a.get('api_name') or ''
            if pc is None:
                continue
            try:
                pc_int = int(pc, 16) if isinstance(pc, str) else pc
            except Exception:
                continue
            if pc_int in pc_count:
                pc_count[pc_int] += 1
                continue
            try:
                line = decode.format_call(
                    api_full, a.get('args', []), a.get('ret_val'),
                    resolve=None, emu=None,
                    arch_bits=64 if image_base > 0xFFFFFFFF else 32)
            except Exception:
                line = api_full
            line = re.sub(r'\s+', ' ', line).strip()[:200]
            pc_to_first[pc_int] = line
            pc_count[pc_int] = 1
            pc_order.append(pc_int)
    for pc_int in pc_order:
        line = pc_to_first[pc_int]
        n = pc_count[pc_int]
        text = line if n == 1 else f'{line}  ×{n}'
        add_comment(pc_int, text, kind='PRE')

    # 2. Labels for MajorFunction[] dispatchers.
    seen_dispatchers = {}
    for mj_index, fn_addr in (mf_table or {}).items():
        if not fn_addr:
            continue
        mj_name = (decode.IRP_MJ[mj_index]
                   if mj_index < len(decode.IRP_MJ)
                   else f'IRP_MJ_{mj_index:02X}')
        # Multiple MJ slots can point to the same dispatcher — group.
        if fn_addr in seen_dispatchers:
            seen_dispatchers[fn_addr].append(mj_name)
        else:
            seen_dispatchers[fn_addr] = [mj_name]
    for fn_addr, names in seen_dispatchers.items():
        if len(names) == 1:
            add_label(fn_addr, f'dispatch_{names[0]}')
        else:
            # Common case: one function services many MJ codes.
            add_label(fn_addr, f'dispatch_common_{len(names)}slots')

    # 3. Labels for DriverObject pointer fields (DriverEntry / Unload /
    # StartIo / Reinit). Some are addr-of-actual-routine; emit labels at
    # the routine address.
    for fld in ('DriverInit', 'DriverUnload', 'DriverStartIo'):
        v = (drv_fields or {}).get(fld, 0)
        if v:
            add_label(v, f'drv_{fld}')

    # 4. Labels for registered callbacks (Cm / Ps / Ob / system threads).
    for cb in callbacks or []:
        try:
            kind, fn_addr, _args = cb
        except Exception:
            continue
        if not fn_addr:
            continue
        # Normalise kind into a label-safe stem.
        if kind.startswith('ProcessNotify'):
            stem = 'cb_PsSetCreateProcessNotifyRoutineEx'
        elif kind.startswith('ThreadNotify'):
            stem = 'cb_PsSetCreateThreadNotifyRoutine'
        elif kind.startswith('LoadImageNotify'):
            stem = 'cb_PsSetLoadImageNotifyRoutine'
        elif kind.startswith('CmCallback'):
            stem = 'cb_CmRegisterCallbackEx'
        elif kind.startswith('ObPreOp'):
            stem = 'cb_ObPreOperation'
        elif kind.startswith('ObPostOp'):
            stem = 'cb_ObPostOperation'
        elif kind == 'SystemThread':
            stem = 'wt_SystemThreadStart'
        else:
            stem = 'cb_' + kind
        add_label(fn_addr, stem)

    # 5. Labels for FLT pre-op callbacks if present in the report.
    # discover_callbacks doesn't emit those, but the IRP-firing phase
    # logs them; we'd need to extract from the trace log text.
    # (Pulled from log lines like "FLT pre-op for IRP_MJ_CREATE @ 0x13720".)
    for m in re.finditer(
            r'FLT pre-op for ([A-Z_0-9x]+) @ 0x([0-9a-fA-F]+)',
            trace_log_text or ''):
        mj_name = m.group(1)
        addr = int(m.group(2), 16)
        add_label(addr, f'flt_preop_{mj_name}')

    # 6. Internal function tracing (--trace-fn) — pull from .jsonl.
    # Each `phase: "internal_fn"` record carries:
    #   pc       — caller's CALL-site address (where to put the EOL)
    #   fn_addr  — callee entry address (where to put the label)
    #   api      — display name
    #   fields   — list of arg renderings
    #   ret      — return value hex string
    #
    # We:
    #   * Deduplicate EOL comments by pc (multiple calls from the same
    #     PC collapse to "internal.NAME(…) ×N"). Distinct field values
    #     across calls are joined with " | " up to the first 200 chars
    #     so the analyst sees varied invocations.
    #   * Add one label per unique fn_addr.
    if jsonl_path:
        try:
            tracefn_pc_seen = {}        # pc -> {api, examples[], count, ret}
            tracefn_fn_addrs = {}       # fn_addr -> api name (first seen)
            with open(jsonl_path, 'r', encoding='utf-8',
                      errors='replace') as _f:
                for line in _f:
                    line = line.strip()
                    if not line.startswith('{'):
                        continue
                    try:
                        rec = json.loads(line)
                    except Exception:
                        continue
                    if rec.get('phase') != 'internal_fn':
                        continue
                    pc = rec.get('pc')
                    if isinstance(pc, str):
                        try:
                            pc = int(pc, 0)
                        except Exception:
                            continue
                    if not isinstance(pc, int):
                        continue
                    fn_addr_v = rec.get('fn_addr')
                    if isinstance(fn_addr_v, str):
                        try:
                            fn_addr_v = int(fn_addr_v, 0)
                        except Exception:
                            fn_addr_v = None
                    api_name = rec.get('api') or 'internal_fn'
                    if fn_addr_v and fn_addr_v not in tracefn_fn_addrs:
                        tracefn_fn_addrs[fn_addr_v] = api_name
                    rendered = (f"internal.{api_name}("
                                + ', '.join(rec.get('fields') or [])
                                + ')')
                    ret = rec.get('ret')
                    if ret:
                        rendered += f' -> {ret}'
                    slot = tracefn_pc_seen.setdefault(pc, {
                        'count': 0, 'examples': [], 'api': api_name,
                    })
                    slot['count'] += 1
                    if rendered not in slot['examples'] \
                            and len(slot['examples']) < 5:
                        slot['examples'].append(rendered)
            # Render EOL comments now that we've collapsed across hits.
            for pc, slot in tracefn_pc_seen.items():
                joined = ' | '.join(slot['examples'])
                if len(joined) > 240:
                    joined = joined[:237] + '…'
                if slot['count'] > 1:
                    joined = f"{joined}  ×{slot['count']}"
                add_comment(pc, joined, kind='PRE')
            # Labels at callee entries.
            for fn_addr_v, api in tracefn_fn_addrs.items():
                add_label(fn_addr_v, f'tracefn_{api}')
        except FileNotFoundError:
            pass
        except Exception as e:
            comments.append((0, 'PRE',
                             f'(ktrace internal_fn parse error: {e})'))

    return comments, labels


def emit(out_path, comments, labels, sha256, class_name=None):
    """Render and write the Java script to out_path."""
    import datetime
    out_path = Path(out_path)
    if class_name is None:
        # Strip .java, sanitize.
        stem = out_path.stem
        class_name = _sanitize_label(stem) or 'KtraceImport'
        # Java class names must start with a letter.
        if not class_name[0].isalpha():
            class_name = 'K' + class_name

    def fmt_comment_row(rva, kind, text):
        return ('        {Long.valueOf(0x%xL), %s, %s},'
                % (rva, _java_string(kind), _java_string(text)))

    def fmt_label_row(rva, name):
        return ('        {Long.valueOf(0x%xL), %s},'
                % (rva, _java_string(name)))

    comments_block = '\n'.join(
        fmt_comment_row(rva, kind, text) for rva, kind, text in comments)
    labels_block = '\n'.join(
        fmt_label_row(rva, name) for rva, name in labels)

    body = _JAVA_HEADER % {
        'sha256': sha256,
        'timestamp': datetime.datetime.now(datetime.timezone.utc).isoformat(
            timespec='seconds'),
        'n_comments': len(comments),
        'n_labels': len(labels),
        'class_name': class_name,
        'comments_block': comments_block,
        'labels_block': labels_block,
    }
    out_path.write_text(body, encoding='utf-8')
    return out_path
