ASM = zerobytes.asm
OBJ = zerobytes.obj
EXE = zerobytes.exe

YASM = "<path>\yasm-1.3.0-win32.exe"
LINK = "<path>\link.exe"

# /fixed gets rid of the .reloc table
LINKFLAGS = /subsystem:windows /fixed /debug:none /entry:main user32.lib kernel32.lib

INSTALLPATH = <path>\mega.exe

all: $(EXE)

$(EXE): $(OBJ)
	@$(LINK) $(OBJ) $(LINKFLAGS) /out:$(EXE)

$(OBJ): $(ASM)
	@$(YASM) -f win32 $< -o $@

clean:
	del $(OBJ) $(EXE)

install: $(EXE)
	copy $(EXE) "$(INSTALLPATH)"
